// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PREFIXTABLE_PREFIXTABLE_H_
#define FLATBUFFERS_GENERATED_PREFIXTABLE_PREFIXTABLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace prefixtable {

struct PrefixEntry;
struct PrefixEntryBuilder;

struct PrefixTable;
struct PrefixTableBuilder;

struct PrefixEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PrefixEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BYTE = 4,
    VT_FREQUENCY = 6
  };
  uint8_t byte() const {
    return GetField<uint8_t>(VT_BYTE, 0);
  }
  uint64_t frequency() const {
    return GetField<uint64_t>(VT_FREQUENCY, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BYTE, 1) &&
           VerifyField<uint64_t>(verifier, VT_FREQUENCY, 8) &&
           verifier.EndTable();
  }
};

struct PrefixEntryBuilder {
  typedef PrefixEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_byte(uint8_t byte) {
    fbb_.AddElement<uint8_t>(PrefixEntry::VT_BYTE, byte, 0);
  }
  void add_frequency(uint64_t frequency) {
    fbb_.AddElement<uint64_t>(PrefixEntry::VT_FREQUENCY, frequency, 0);
  }
  explicit PrefixEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PrefixEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PrefixEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PrefixEntry> CreatePrefixEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t byte = 0,
    uint64_t frequency = 0) {
  PrefixEntryBuilder builder_(_fbb);
  builder_.add_frequency(frequency);
  builder_.add_byte(byte);
  return builder_.Finish();
}

struct PrefixTable FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PrefixTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<prefixtable::PrefixEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<prefixtable::PrefixEntry>> *>(VT_ENTRIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct PrefixTableBuilder {
  typedef PrefixTable Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<prefixtable::PrefixEntry>>> entries) {
    fbb_.AddOffset(PrefixTable::VT_ENTRIES, entries);
  }
  explicit PrefixTableBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PrefixTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PrefixTable>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PrefixTable> CreatePrefixTable(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<prefixtable::PrefixEntry>>> entries = 0) {
  PrefixTableBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PrefixTable> CreatePrefixTableDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<prefixtable::PrefixEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<prefixtable::PrefixEntry>>(*entries) : 0;
  return prefixtable::CreatePrefixTable(
      _fbb,
      entries__);
}

inline const prefixtable::PrefixTable *GetPrefixTable(const void *buf) {
  return ::flatbuffers::GetRoot<prefixtable::PrefixTable>(buf);
}

inline const prefixtable::PrefixTable *GetSizePrefixedPrefixTable(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<prefixtable::PrefixTable>(buf);
}

template <bool B = false>
inline bool VerifyPrefixTableBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<prefixtable::PrefixTable>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedPrefixTableBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<prefixtable::PrefixTable>(nullptr);
}

inline void FinishPrefixTableBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<prefixtable::PrefixTable> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPrefixTableBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<prefixtable::PrefixTable> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace prefixtable

#endif  // FLATBUFFERS_GENERATED_PREFIXTABLE_PREFIXTABLE_H_
